name: CI Workflow .NET Workflow Dispatch

on:
  workflow_dispatch:
    inputs:
      os:
        description: 'Choose the operating system'
        required: true
        default: 'ubuntu-latest'
        type: choice
        options:
          - ubuntu-latest
          - windows-latest
          - macos-latest

jobs:
  build:
    runs-on: ${{ github.event.inputs.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0'

    - name: Restore NuGet packages on Ubuntu
      if: runner.os == 'Linux'
      run: dotnet restore

    - name: Restore NuGet packages on Windows
      if: runner.os == 'Windows'
      run: dotnet restore

    - name: Restore NuGet packages on macOS
      if: runner.os == 'macOS'
      run: dotnet restore

    - name: Build on Ubuntu
      if: runner.os == 'Linux'
      run: dotnet build --configuration Release --no-restore

    - name: Build on Windows
      if: runner.os == 'Windows'
      run: dotnet build --configuration Release --no-restore

    - name: Build on macOS
      if: runner.os == 'macOS'
      run: dotnet build --configuration Release --no-restore

    - name: Test on Ubuntu
      if: runner.os == 'Linux'
      run: dotnet test --no-restore --verbosity normal

    - name: Test on Windows
      if: runner.os == 'Windows'
      run: dotnet test --no-restore --verbosity normal

    - name: Test on macOS
      if: runner.os == 'macOS'
      run: dotnet test --no-restore --verbosity normal
